# Use the official PostgreSQL image as the base image
FROM postgres:latest

ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB postgres

# Set the working directory in the container
WORKDIR /app

# Copy the initialization script to the container
COPY init.sql /docker-entrypoint-initdb.d/init.sql
