# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x15\n\x13RandomNumberRequest\"&\n\x14RandomNumberResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"$\n\x06Number\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06number\x18\x02 \x01(\x05\x32]\n\tMyService\x12P\n\x0fGetRandomNumber\x12\x1c.example.RandomNumberRequest\x1a\x1d.example.RandomNumberResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANDOMNUMBERREQUEST._serialized_start=26
  _RANDOMNUMBERREQUEST._serialized_end=47
  _RANDOMNUMBERRESPONSE._serialized_start=49
  _RANDOMNUMBERRESPONSE._serialized_end=87
  _EMPTY._serialized_start=89
  _EMPTY._serialized_end=96
  _NUMBER._serialized_start=98
  _NUMBER._serialized_end=134
  _MYSERVICE._serialized_start=136
  _MYSERVICE._serialized_end=229
# @@protoc_insertion_point(module_scope)
